"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
truncation_length = 3
truncate_to_repo = true
style = 'bold cyan'

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'

[package]
disabled = true

[ruby]
disabled = true

[nix_shell]
disabled = true

[python]
disabled = true

[buf]
disabled = true

[nodejs]
symbol = ''
version_format = 'v${major}.${minor}'
format = '[$symbol($version )]($style)'

[golang]
symbol = ''
version_format = 'v${major}.${minor}'
format = '[$symbol($version )]($style)'

[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style)'

[kubernetes]
disabled = false
symbol = '⎈'
format = ' [$symbol$context( \($namespace\))]($style) '
detect_folders = ['k8s', 'kube', 'overlays']
detect_files = ['k9s.yaml']

[kubernetes.context_aliases]
"dev-cluster" = "DEV"

[[kubernetes.contexts]]
context_pattern = "dev.*"
style = "bold red"

[[kubernetes.contexts]]
context_pattern = "local.*"
style = "bold green"

[git_branch]
symbol = ''
format = '[$branch(:$remote_branch)]($style) '
truncation_length = 20

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'yellow'

[git_metrics]
disabled = false

[direnv]
disabled = false
symbol = ''
allowed_msg = ''
loaded_msg = '✓'
not_allowed_msg = '!'
format = '[$loaded$allowed]($style) '

[mise]
disabled = false
symbol = ''
style = 'purple'
format = '[$health]($style)'
healthy_symbol = ''
unhealthy_symbol = '!'
