tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "apache-arrow-glib"
brew "boost"
brew "gdal"
brew "gobject-introspection"
brew "harfbuzz"
brew "pango"
brew "postgresql@14", restart_service: true
brew "postgis"
brew "ykman"
cask "adoptopenjdk8"
cask "chromedriver"
