#!/bin/sh

set -e

if [[ ! $1 =~ .+:.+ ]]; then 
  echo "Usage: git cor username:branchname"
  exit
fi

# Check out a remote branch
# $ git co username:branch
repo_origin=$(git remote get-url origin)
repo_name=$(basename ${repo_origin} .git)

arg=(${1//:/ })
user_name=${arg[0]}
remote_branch_name=${arg[1]}
local_branch_name=${arg[2]:-$remote_branch_name} # Allow local branch to be specified, default to remote branch

# Add remote if it doesn't exist already
if ! git config remote.${user_name}.url > /dev/null; then
  git remote add ${user_name} git@github.com:${user_name}/${repo_name}.git
fi
git fetch ${user_name}
git checkout -b ${remote_branch_name} ${user_name}/${remote_branch_name}r
